# Generated by Django 5.1.2 on 2024-11-02 16:14

import autoslug.fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Blogcategory/",
                        verbose_name="Resim",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "img_alt",
                    models.CharField(max_length=255, verbose_name="Resim Alt Metni"),
                ),
                (
                    "img_title",
                    models.CharField(max_length=255, verbose_name="Resim Başlığı"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi"),
                ),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategori",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Başlık")),
                (
                    "short_description",
                    models.CharField(max_length=500, verbose_name="Kısa Açıklama"),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Açıklama"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/",
                        verbose_name="Banner Resmi",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="title",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Görüntüleme Sayısı"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_blogs",
                        to="blog.category",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Bloglar",
                "ordering": ["-created_at"],
            },
        ),
    ]
