# Generated by Django 5.1.2 on 2024-11-02 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "İteşim",
                "verbose_name_plural": "İteşim",
            },
        ),
        migrations.CreateModel(
            name="HomeMainBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000, verbose_name="Başlık")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Alt Başlık",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Resim boyutları 1714x584 piksel olmalıdır.",
                        upload_to="banners/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["webp", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        choices=[
                            ("red", "Kırmızı"),
                            ("blue", "Mavi"),
                            ("green", "Yeşil"),
                            ("yellow", "Sarı"),
                            ("white", "Beyaz"),
                            ("black", "Siyah"),
                        ],
                        default="black",
                        max_length=1000,
                        verbose_name="Metin Rengi",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "title_position",
                    models.CharField(
                        choices=[
                            ("centerize", "Orta"),
                            ("right", "Sağ"),
                            ("left", "Sol"),
                        ],
                        default="center",
                        max_length=1000,
                        verbose_name="Başlık Pozisyonu",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=2000, null=True, verbose_name="Bağlantı"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi"),
                ),
            ],
            options={
                "verbose_name": "Ana Banner",
                "verbose_name_plural": "Ana Banner",
            },
        ),
        migrations.CreateModel(
            name="HomePageBannerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200, null=True)),
                ("image", models.ImageField(upload_to="banner_images/")),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("right", "Right"),
                            ("slider", "Slider"),
                        ],
                        default="slider",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Ana Sayfa Banner2",
                "verbose_name_plural": "Ana Sayfa Banner2",
            },
        ),
        migrations.CreateModel(
            name="HomeSubBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choose",
                    models.CharField(
                        choices=[
                            ("banner1", "Banner 1"),
                            ("banner2", "Banner 2"),
                            ("banner3", "Banner 3"),
                            ("banner4", "Banner 4"),
                        ],
                        max_length=20,
                        verbose_name="Seçim",
                    ),
                ),
                ("title", models.CharField(max_length=1000, verbose_name="Başlık")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Alt Başlık",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="banners/", verbose_name="Resim"),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=2000, null=True, verbose_name="Bağlantı"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi"),
                ),
                (
                    "text_color",
                    models.CharField(
                        choices=[
                            ("red", "Kırmızı"),
                            ("blue", "Mavi"),
                            ("green", "Yeşil"),
                            ("yellow", "Sarı"),
                            ("white", "Beyaz"),
                            ("black", "Siyah"),
                        ],
                        default="black",
                        max_length=1000,
                        verbose_name="Metin Rengi",
                    ),
                ),
            ],
            options={
                "verbose_name": "ÜrünDetay Banner",
                "verbose_name_plural": "ÜrünDetay Banner",
            },
        ),
        migrations.CreateModel(
            name="Request_Log_Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_data", models.TextField(blank=True, null=True)),
                ("response_data", models.TextField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("order_number", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("linkedin", "Linkedin"),
                            ("youtube", "YouTube"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Adı",
                    ),
                ),
                ("link", models.URLField(verbose_name="Bağlantı")),
            ],
            options={
                "verbose_name": "Sosyal Medya",
                "verbose_name_plural": "Sosyal Medya",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="E-Posta Adresi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Aktif mi?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonelik",
                "verbose_name_plural": "Abonelikler",
            },
        ),
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="teamMembers/")),
                ("full_name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "1. Seviye"),
                            (2, "2. Seviye"),
                            (3, "3. Seviye"),
                            (4, "4. Seviye"),
                            (5, "5. Seviye"),
                            (5, "5. Seviye"),
                        ],
                        default=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("facebook_link", models.URLField(blank=True, null=True)),
                ("twitter_link", models.URLField(blank=True, null=True)),
                ("instagram_link", models.URLField(blank=True, null=True)),
                ("linkedin_link", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Takım",
                "verbose_name_plural": "Takım",
            },
        ),
    ]
