# Generated by Django 5.1.2 on 2024-11-14 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customerauth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_code", models.CharField(max_length=2, unique=True)),
                ("status_description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ShippingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Müşteri Adı"
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Alıcı Kodu"
                    ),
                ),
                ("province_name", models.CharField(max_length=100, verbose_name="İl")),
                ("county_name", models.CharField(max_length=100, verbose_name="İlçe")),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Mahalle"
                    ),
                ),
                ("address", models.TextField(verbose_name="Adres")),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="TC / Vergi No"
                    ),
                ),
                (
                    "tax_office",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Vergi Dairesi"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Sipariş Numarası"
                    ),
                ),
                (
                    "branch_code",
                    models.CharField(
                        default="34", max_length=50, verbose_name="Şube Kodu"
                    ),
                ),
                (
                    "start_branch",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Çıkış Şubesi"
                    ),
                ),
                (
                    "region_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Dağıtım Bölgesi Kodu"
                    ),
                ),
                (
                    "courrier_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Kurye Kodu"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=100, unique=True, verbose_name="Barkod"
                    ),
                ),
                (
                    "sub_barcode",
                    models.TextField(blank=True, verbose_name="Alt Barkod"),
                ),
                (
                    "amount_type_id",
                    models.IntegerField(default=3, verbose_name="Ödeme Türü"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tutar",
                    ),
                ),
                (
                    "currency_name",
                    models.CharField(
                        blank=True,
                        default="TRY",
                        max_length=10,
                        verbose_name="Para Birimi",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="İçerik")),
                (
                    "sender_note",
                    models.TextField(blank=True, verbose_name="Gönderici Notu"),
                ),
                (
                    "quantity",
                    models.IntegerField(default=1, verbose_name="Paket Miktar"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ağırlık (Kg)",
                    ),
                ),
                (
                    "total_bulk",
                    models.IntegerField(default=1, verbose_name="Toplam Desi"),
                ),
                (
                    "verification_code",
                    models.CharField(
                        max_length=10, verbose_name="Alıcı Teslim Şifresi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "record_id",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Kayıt Numarası"
                    ),
                ),
                (
                    "shipping_url",
                    models.URLField(null=True, verbose_name="Kargo Takip Url"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_orders",
                        to="customerauth.order",
                    ),
                ),
                (
                    "shipping_status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shipping.cargostatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=100)),
                ("sender_barcode", models.CharField(max_length=100)),
                ("sender_name", models.CharField(max_length=100)),
                ("acceptance_date", models.DateField()),
                ("sender_address", models.TextField()),
                ("sender_city", models.CharField(blank=True, max_length=100)),
                ("sender_phone", models.CharField(blank=True, max_length=15)),
                (
                    "collection_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("weight_bulk", models.DecimalField(decimal_places=2, max_digits=10)),
                ("package_quantity", models.IntegerField()),
                ("recipient_name", models.CharField(max_length=100)),
                ("status_number", models.CharField(max_length=100)),
                ("recipient_address", models.TextField()),
                ("recipient_district", models.CharField(max_length=100)),
                ("recipient_city", models.CharField(max_length=100)),
                ("result_status", models.CharField(max_length=50)),
                ("result_description", models.TextField()),
                ("recipient_phone", models.CharField(max_length=100)),
                ("result_date", models.DateField()),
                ("arrival_branch", models.CharField(max_length=100)),
                ("exit_number", models.CharField(max_length=100)),
                ("tracking_url", models.URLField()),
                ("movements", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_movements",
                        to="customerauth.order",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shipping.cargostatus",
                    ),
                ),
                (
                    "shipping_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_movements",
                        to="shipping.shippingorder",
                    ),
                ),
            ],
        ),
    ]
