# Generated by Django 5.1.2 on 2024-11-02 16:49

import autoslug.fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="Brand/", verbose_name="Resim"
                    ),
                ),
                (
                    "img_alt",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Resim Alt Metni",
                    ),
                ),
                (
                    "img_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Resim Başlığı",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi"),
                ),
            ],
            options={
                "verbose_name": "Marka",
                "verbose_name_plural": "Marka",
            },
        ),
        migrations.CreateModel(
            name="HomeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="home_models/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("img_alt", models.CharField(max_length=255, unique=True)),
                ("img_title", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="HomeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="home_types/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("img_alt", models.CharField(max_length=255, unique=True)),
                ("img_title", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="room_types/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("img_alt", models.CharField(max_length=255, unique=True)),
                ("img_title", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpaceDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="space_definitions/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("img_alt", models.CharField(max_length=255, unique=True)),
                ("img_title", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Şirket Adı"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Adres"),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Vergi Kimlik Numarası (VKN)",
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True,
                        max_length=34,
                        null=True,
                        verbose_name="IBAN Numarası",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Telefon Numarası",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="E-Posta Adresi",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Yetkili Kişi",
                    ),
                ),
                (
                    "tax_office",
                    models.TextField(
                        blank=True, null=True, verbose_name="Vergi Dairesi"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Web Sitesi"),
                ),
                (
                    "invoice_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Fatura Notları"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tedarikçi",
                "verbose_name_plural": "Tedarikçiler",
            },
        ),
        migrations.CreateModel(
            name="TimeRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="time_range/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("img_alt", models.CharField(max_length=255, unique=True)),
                ("img_title", models.CharField(max_length=255, unique=True)),
                ("min_value", models.IntegerField(default=0)),
                ("max_value", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="category/",
                        verbose_name="Resim",
                    ),
                ),
                (
                    "mainImage",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="category/",
                        verbose_name="Ana Resim",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "img_alt",
                    models.CharField(max_length=255, verbose_name="Resim Alt Metni"),
                ),
                (
                    "img_title",
                    models.CharField(max_length=255, verbose_name="Resim Başlığı"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="Üst Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriler",
                "verbose_name_plural": "Kategoiler",
                "unique_together": {("slug", "parent")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Ad")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Açıklama"
                    ),
                ),
                (
                    "information",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Bilgi"
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Satış Fiyatı"
                    ),
                ),
                (
                    "selling_old_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Eski Satış Fiyatı",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Alış Fiyatı",
                    ),
                ),
                (
                    "in_stock",
                    models.IntegerField(default=10, verbose_name="Stokta Var"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi"),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Öne Çıkan"),
                ),
                (
                    "best_seller",
                    models.BooleanField(default=False, verbose_name="En Çok Satılan"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Görüntülenme Sayısı"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.brand",
                        verbose_name="Marka",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "home_models",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="products.homemodel",
                        verbose_name="Ev Modelleri",
                    ),
                ),
                (
                    "home_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="products.hometype",
                        verbose_name="Ev Tipleri",
                    ),
                ),
                (
                    "related",
                    models.ManyToManyField(
                        blank=True,
                        related_name="related_product_set",
                        to="products.product",
                    ),
                ),
                (
                    "room_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="products.roomtype",
                        verbose_name="Oda Tipleri",
                    ),
                ),
                (
                    "space_definitions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="products.spacedefinition",
                        verbose_name="Alan Tanımları",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.supplier",
                        verbose_name="Tedarikçi",
                    ),
                ),
                (
                    "time_ranges",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="products.timerange",
                        verbose_name="Zaman Aralıkları",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürünler",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="product_images/", verbose_name="Resim"
                    ),
                ),
                (
                    "img_alt",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Resim Alt Metni"
                    ),
                ),
                (
                    "img_title",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Resim Başlığı"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_products",
                        to="products.product",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Resimleri",
                "verbose_name_plural": "Ürün Resimleri",
            },
        ),
        migrations.CreateModel(
            name="ProductRentalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                            ("16", "16"),
                            ("17", "17"),
                            ("18", "18"),
                            ("19", "19"),
                            ("20", "20"),
                            ("21", "21"),
                            ("22", "22"),
                            ("23", "23"),
                            ("24", "24"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Ay",
                    ),
                ),
                (
                    "rental_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Kiralama Fiyatı"
                    ),
                ),
                (
                    "rental_old_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Eski Kiralama Fiyatı",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_products_price",
                        to="products.product",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Kiralama Fiyatı",
                "verbose_name_plural": "Ürün Kiralama Fiyatı",
            },
        ),
    ]
