# Generated by Django 5.1.2 on 2024-11-03 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_productreview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductReview",
        ),
    ]
