# Generated by Django 5.1.2 on 2024-11-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_cart_cartitem_cart_items_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="iconSvg",
            field=models.TextField(blank=True, null=True, verbose_name="Katgori İkon"),
        ),
    ]
