# Generated by Django 5.1.2 on 2024-12-14 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_productreview_comment_question_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="user",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
