# Generated by Django 5.1.2 on 2024-12-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
