# Generated by Django 5.1.2 on 2024-12-15 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_cart_session_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
    ]
